# Generated by Django 4.2.7 on 2023-11-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_page_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('paggge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.page')),
                ('like', models.IntegerField()),
            ],
            bases=('myapp.page',),
        ),
    ]
