# Generated by Django 4.0.7 on 2023-04-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stName', models.CharField(max_length=40)),
                ('stEmail', models.CharField(max_length=80)),
            ],
        ),
    ]
