# Generated by Django 4.0.7 on 2023-04-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stPassword',
            field=models.CharField(default='not available', max_length=10),
        ),
    ]
